name: Pendula
options:
  bundleIdPrefix: dev.tokizuoh
  developmentLanguage: ja
  deploymentTarget:
    iOS: 13.0
  xcodeVersion: "12.3"

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1

targets:
  Pendula:
    type: application
    platform: iOS
    sources:
      - Pendula
    settings:
      base:
        INFOPLIST_FILE: Pendula/Info.plist
        DEVELOPMENT_LANGUAGE: jp

  PendulaTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PendulaTests
    settings:
      base:
        INFOPLIST_FILE: PendulaTests/Info.plist
        DEVELOPMENT_LANGUAGE: jp
    dependencies:
      - target: Pendula

  PendulaUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - PendulaUITests
    settings:
      base:
        INFOPLIST_FILE: PendulaUITests/Info.plist
        DEVELOPMENT_LANGUAGE: jp
    dependencies:
      - target: Pendula

schemes:
  Pendula:
    build:
      targets:
        Pendula: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Pendula
      targets:
        - name: PendulaTests
          parallelizable: true
          randomExecutionOrder: true
        - name: PendulaUITests
          parallelizable: true
          randomExecutionOrder: true
      profile:
        config: Release
      analyze:
        config: Debug
      archive:
        config: Release